name: SonarCloud workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accurate analysis history

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: itcs472
          projectKey: SunnyRichman_2024-ITCS472-SE-assignment
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
